package bigBrew;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author JULIA
 */
public class LogIn_Page extends javax.swing.JFrame {

    int attempt = 2;
    
    public LogIn_Page() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/bigBrew/icons/icon.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        logIn_panel = new javax.swing.JPanel();
        pass_txt = new javax.swing.JLabel();
        welcome_txt = new javax.swing.JLabel();
        username_txt = new javax.swing.JLabel();
        pass_txtfield = new javax.swing.JPasswordField();
        username_txtfield = new javax.swing.JTextField();
        logIn_button = new javax.swing.JButton();
        title_panel = new javax.swing.JPanel();
        bb_txt = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log In");
        setName("logIn_frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 500));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new java.awt.BorderLayout());

        logIn_panel.setBackground(new java.awt.Color(255, 255, 255));
        logIn_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        pass_txt.setForeground(new java.awt.Color(0, 0, 0));
        pass_txt.setText("Password:");
        logIn_panel.add(pass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 30));

        welcome_txt.setFont(new java.awt.Font("Studebaker NF", 1, 48)); // NOI18N
        welcome_txt.setForeground(new java.awt.Color(187, 111, 26));
        welcome_txt.setText("WELCOME!");
        logIn_panel.add(welcome_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 210, 70));

        username_txt.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        username_txt.setForeground(new java.awt.Color(0, 0, 0));
        username_txt.setText("Username:");
        logIn_panel.add(username_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 30));
        logIn_panel.add(pass_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 170, 30));
        logIn_panel.add(username_txtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, 30));

        logIn_button.setBackground(new java.awt.Color(38, 38, 38));
        logIn_button.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        logIn_button.setForeground(new java.awt.Color(255, 255, 255));
        logIn_button.setText("Log In");
        logIn_button.setAlignmentY(0.0F);
        logIn_button.setBorder(null);
        logIn_button.setBorderPainted(false);
        logIn_button.setContentAreaFilled(false);
        logIn_button.setFocusPainted(false);
        logIn_button.setFocusable(false);
        logIn_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logIn_button.setIconTextGap(0);
        logIn_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        logIn_button.setOpaque(true);
        logIn_button.setPreferredSize(new java.awt.Dimension(180, 40));
        logIn_button.setRequestFocusEnabled(false);
        logIn_button.setRolloverEnabled(false);
        logIn_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logIn_buttonActionPerformed(evt);
            }
        });
        logIn_panel.add(logIn_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));
        ButtonMouseListener settings_listener = new ButtonMouseListener(logIn_button);
        logIn_button.addMouseListener(settings_listener);

        bg.add(logIn_panel, java.awt.BorderLayout.CENTER);

        title_panel.setBackground(new java.awt.Color(25, 25, 25));
        title_panel.setPreferredSize(new java.awt.Dimension(360, 0));
        title_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bb_txt.setFont(new java.awt.Font("Studebaker NF", 1, 48)); // NOI18N
        bb_txt.setForeground(new java.awt.Color(255, 255, 255));
        bb_txt.setText("BIG BREW");
        title_panel.add(bb_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, 70));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigBrew/icons/logIn_icon.png"))); // NOI18N
        title_panel.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        bg.add(title_panel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logIn_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logIn_buttonActionPerformed
        String system_username = "Admin";
        String system_pass = "654321";
        
        String entered_username = username_txtfield.getText();
        String entered_pass = pass_txtfield.getText();
        boolean correctInfo = entered_username.equals(system_username) && entered_pass.equals(system_pass);
        boolean fieldsCleared = false;
            
           if (correctInfo) {
              dispose();
              MainFrame main_frame = new MainFrame();
              main_frame.setVisible(true);
              attempt++; // used prevent from decrementing again if there's only one try left 
         } else if(!(correctInfo) && attempt >=1){
              JOptionPane.showMessageDialog(null, " Invalid username or password.\n    You have " + attempt + " attempt/s left.", "Error", JOptionPane.WARNING_MESSAGE);

              // Clear text fields after an incorrect attempt
              if (!fieldsCleared) {
                  username_txtfield.setText("");
                  pass_txtfield.setText("");
                  fieldsCleared = true;
               } 
            }
           
              if (attempt == 0)
               {
                 JOptionPane.showMessageDialog(null, "You used up all your attempts. \n Try again later.", "Error", JOptionPane.ERROR_MESSAGE);
                 System.exit(0);
               }
               attempt--;
    }//GEN-LAST:event_logIn_buttonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LogIn_Page().setVisible(true);   
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bb_txt;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel icon;
    private javax.swing.JButton logIn_button;
    private javax.swing.JPanel logIn_panel;
    private javax.swing.JLabel pass_txt;
    private javax.swing.JPasswordField pass_txtfield;
    private javax.swing.JPanel title_panel;
    private javax.swing.JLabel username_txt;
    private javax.swing.JTextField username_txtfield;
    private javax.swing.JLabel welcome_txt;
    // End of variables declaration//GEN-END:variables
}
