package bigBrew;

import java.awt.CardLayout;
import java.awt.Toolkit;

import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;


public final class MainFrame extends javax.swing.JFrame {
   
    CardLayout card;
    CardLayout menu;
    CardLayout add_fields;
    CardLayout edit_fields;
    LocalDate currentDate;

    public MainFrame() {
        initComponents();
        setDateTime();
        
        // changes the icon image of JFrame
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/bigBrew/icons/icon.png"))); 
        setTitle("Big Brew"); // sets the title of JFrame

        card = (CardLayout) main_panel.getLayout();
        menu = (CardLayout) modification_panel.getLayout();
        add_fields = (CardLayout) tf_bgpanel.getLayout();
        edit_fields = (CardLayout) tf_bgpanel1.getLayout();
        
        DatabaseHandler.orderUpdateProductName(order_category_cbb, order_table_pname); // para sa table ng Product Name sa Order tab
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_panel = new javax.swing.JPanel();
        brand_name = new javax.swing.JLabel();
        brand_logo = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        order_button = new javax.swing.JButton();
        menu_button = new javax.swing.JButton();
        history_button = new javax.swing.JButton();
        logOut_button = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        order_panel = new javax.swing.JPanel();
        order_title = new javax.swing.JLabel();
        order_bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        actual_date_label = new javax.swing.JLabel();
        order_size_cbb = new javax.swing.JComboBox<>();
        order_category_cbb = new javax.swing.JComboBox<>();
        order_table_scrollpane = new javax.swing.JScrollPane();
        currentOrder_table = new javax.swing.JTable();
        qty_spinner = new javax.swing.JSpinner();
        label_mprice1 = new javax.swing.JLabel();
        label_mprice2 = new javax.swing.JLabel();
        size_label = new javax.swing.JLabel();
        table_scrollpane2 = new javax.swing.JScrollPane();
        order_table_pname = new javax.swing.JTable();
        category_txt = new javax.swing.JLabel();
        time_label = new javax.swing.JLabel();
        actual_time_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt_area = new javax.swing.JTextArea();
        cash_txtField = new javax.swing.JTextField();
        total_text = new javax.swing.JLabel();
        cash_text = new javax.swing.JLabel();
        total_label = new javax.swing.JLabel();
        change_label = new javax.swing.JLabel();
        orderAdd_button = new javax.swing.JButton();
        orderReset_button = new javax.swing.JButton();
        orderRemove_button = new javax.swing.JButton();
        receipt_button = new javax.swing.JButton();
        orderClear_button = new javax.swing.JButton();
        menu_panel = new javax.swing.JPanel();
        menu_title = new javax.swing.JLabel();
        mcontent_panel = new javax.swing.JPanel();
        category_combobox = new javax.swing.JComboBox<>();
        add_button = new javax.swing.JButton();
        edit_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        table_scrollpane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        modification_panel = new javax.swing.JPanel();
        empty_panel = new javax.swing.JPanel();
        add_panel = new javax.swing.JPanel();
        bg_panel = new javax.swing.JPanel();
        save_btn = new javax.swing.JButton();
        add_text = new javax.swing.JLabel();
        add_cbb = new javax.swing.JComboBox<>();
        tf_bgpanel = new javax.swing.JPanel();
        three_tf = new javax.swing.JPanel();
        add_tf1 = new javax.swing.JTextField();
        add_tf2 = new javax.swing.JTextField();
        add_tf3 = new javax.swing.JTextField();
        two_tf = new javax.swing.JPanel();
        add_tf4 = new javax.swing.JTextField();
        add_tf5 = new javax.swing.JTextField();
        label_name = new javax.swing.JLabel();
        label_mprice = new javax.swing.JLabel();
        label_gprice = new javax.swing.JLabel();
        label_category = new javax.swing.JLabel();
        label_name1 = new javax.swing.JLabel();
        label_price = new javax.swing.JLabel();
        edit_panel = new javax.swing.JPanel();
        bg_panel1 = new javax.swing.JPanel();
        update_button = new javax.swing.JButton();
        update_txt = new javax.swing.JLabel();
        update_cbb = new javax.swing.JComboBox<>();
        item_cbb = new javax.swing.JComboBox<>();
        tf_bgpanel1 = new javax.swing.JPanel();
        two_tf1 = new javax.swing.JPanel();
        edit_tf1 = new javax.swing.JTextField();
        edit_tf2 = new javax.swing.JTextField();
        one_tf1 = new javax.swing.JPanel();
        edit_tf3 = new javax.swing.JTextField();
        label_newGprice = new javax.swing.JLabel();
        label_name2 = new javax.swing.JLabel();
        label_category1 = new javax.swing.JLabel();
        label_newPrice = new javax.swing.JLabel();
        label_newMprice = new javax.swing.JLabel();
        history_panel = new javax.swing.JPanel();
        history_title = new javax.swing.JLabel();
        history_bgPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        history_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("MainFrame"); // NOI18N
        setResizable(false);

        side_panel.setBackground(new java.awt.Color(38, 38, 38));
        side_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brand_name.setFont(new java.awt.Font("Studebaker NF", 1, 24)); // NOI18N
        brand_name.setForeground(new java.awt.Color(240, 240, 240));
        brand_name.setText("BIG BREW");
        side_panel.add(brand_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 45, -1, -1));

        brand_logo.setBackground(new java.awt.Color(38, 38, 38));
        brand_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigBrew/icons/Logo1.1.png"))); // NOI18N
        side_panel.add(brand_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 17, -1, -1));

        line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigBrew/icons/line.png"))); // NOI18N
        line.setText("jLabel3");
        side_panel.add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 76, 98, 10));

        order_button.setBackground(new java.awt.Color(38, 38, 38));
        order_button.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        order_button.setForeground(new java.awt.Color(240, 240, 240));
        order_button.setText("Order");
        order_button.setAlignmentY(0.0F);
        order_button.setBorder(null);
        order_button.setBorderPainted(false);
        order_button.setContentAreaFilled(false);
        order_button.setFocusPainted(false);
        order_button.setFocusable(false);
        order_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        order_button.setIconTextGap(0);
        order_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        order_button.setPreferredSize(new java.awt.Dimension(180, 40));
        order_button.setRequestFocusEnabled(false);
        order_button.setRolloverEnabled(false);
        order_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_buttonActionPerformed(evt);
            }
        });
        side_panel.add(order_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        ButtonMouseListener order_listener = new ButtonMouseListener(order_button);
        order_button.addMouseListener(order_listener);

        menu_button.setBackground(new java.awt.Color(38, 38, 38));
        menu_button.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        menu_button.setForeground(new java.awt.Color(240, 240, 240));
        menu_button.setText("Menu");
        menu_button.setAlignmentY(0.0F);
        menu_button.setBorder(null);
        menu_button.setBorderPainted(false);
        menu_button.setContentAreaFilled(false);
        menu_button.setFocusPainted(false);
        menu_button.setFocusable(false);
        menu_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_button.setIconTextGap(0);
        menu_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        menu_button.setPreferredSize(new java.awt.Dimension(180, 40));
        menu_button.setRequestFocusEnabled(false);
        menu_button.setRolloverEnabled(false);
        menu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buttonActionPerformed(evt);
            }
        });
        side_panel.add(menu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        ButtonMouseListener menu_listener = new ButtonMouseListener(menu_button);
        menu_button.addMouseListener(menu_listener);

        history_button.setBackground(new java.awt.Color(38, 38, 38));
        history_button.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        history_button.setForeground(new java.awt.Color(240, 240, 240));
        history_button.setText("History");
        history_button.setAlignmentY(0.0F);
        history_button.setBorder(null);
        history_button.setBorderPainted(false);
        history_button.setContentAreaFilled(false);
        history_button.setFocusPainted(false);
        history_button.setFocusable(false);
        history_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        history_button.setIconTextGap(0);
        history_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        history_button.setPreferredSize(new java.awt.Dimension(180, 40));
        history_button.setRequestFocusEnabled(false);
        history_button.setRolloverEnabled(false);
        history_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history_buttonActionPerformed(evt);
            }
        });
        side_panel.add(history_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        ButtonMouseListener history_listener = new ButtonMouseListener(history_button);
        history_button.addMouseListener(history_listener);

        logOut_button.setBackground(new java.awt.Color(38, 38, 38));
        logOut_button.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        logOut_button.setForeground(new java.awt.Color(240, 240, 240));
        logOut_button.setText("Log Out");
        logOut_button.setAlignmentY(0.0F);
        logOut_button.setBorder(null);
        logOut_button.setBorderPainted(false);
        logOut_button.setContentAreaFilled(false);
        logOut_button.setFocusPainted(false);
        logOut_button.setFocusable(false);
        logOut_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logOut_button.setIconTextGap(0);
        logOut_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        logOut_button.setPreferredSize(new java.awt.Dimension(180, 40));
        logOut_button.setRequestFocusEnabled(false);
        logOut_button.setRolloverEnabled(false);
        logOut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOut_buttonActionPerformed(evt);
            }
        });
        side_panel.add(logOut_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));
        ButtonMouseListener log_out_listener = new ButtonMouseListener(logOut_button);
        logOut_button.addMouseListener(log_out_listener);

        main_panel.setBackground(new java.awt.Color(255, 102, 102));
        main_panel.setLayout(new java.awt.CardLayout());

        order_panel.setBackground(new java.awt.Color(240, 240, 240));
        order_panel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        order_panel.setLayout(new java.awt.BorderLayout());

        order_title.setBackground(new java.awt.Color(187, 111, 26));
        order_title.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        order_title.setForeground(new java.awt.Color(255, 255, 255));
        order_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        order_title.setText("ORDER");
        order_title.setOpaque(true);
        order_title.setPreferredSize(new java.awt.Dimension(0, 60));
        order_panel.add(order_title, java.awt.BorderLayout.PAGE_START);

        order_bg.setBackground(new java.awt.Color(255, 255, 255));
        order_bg.setFocusable(false);
        order_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Date: ");
        order_bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 70, 30));

        actual_date_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        actual_date_label.setForeground(new java.awt.Color(51, 51, 51));
        order_bg.add(actual_date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 240, 30));

        order_size_cbb.setBackground(new java.awt.Color(255, 255, 255));
        order_size_cbb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        order_size_cbb.setForeground(new java.awt.Color(51, 51, 51));
        order_size_cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medio", "Grande" }));
        order_size_cbb.setFocusable(false);
        order_bg.add(order_size_cbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, 40));

        order_category_cbb.setBackground(new java.awt.Color(255, 255, 255));
        order_category_cbb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        order_category_cbb.setForeground(new java.awt.Color(51, 51, 51));
        order_category_cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milk Tea", "Iced Coffee", "Fruit Tea", "Hot Brew", "Praf", "Add-Ons" }));
        order_category_cbb.setFocusable(false);
        order_category_cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_category_cbbActionPerformed(evt);
            }
        });
        order_bg.add(order_category_cbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 220, 40));

        order_table_scrollpane.setBackground(new java.awt.Color(255, 255, 255));
        order_table_scrollpane.setBorder(null);
        order_table_scrollpane.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        order_table_scrollpane.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N

        currentOrder_table.setAutoCreateRowSorter(true);
        currentOrder_table.setBackground(new java.awt.Color(255, 255, 255));
        currentOrder_table.setForeground(new java.awt.Color(51, 51, 51));
        currentOrder_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Size", "Quantity", "Price"
            }
        ));
        currentOrder_table.setFocusable(false);
        currentOrder_table.setName(""); // NOI18N
        currentOrder_table.getTableHeader().setReorderingAllowed(false);
        order_table_scrollpane.setViewportView(currentOrder_table);
        table.setRowHeight(table.getRowHeight()+20);

        order_bg.add(order_table_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 370, 100));

        qty_spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        qty_spinner.setFocusable(false);
        order_bg.add(qty_spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 100, 40));

        label_mprice1.setBackground(new java.awt.Color(51, 51, 51));
        label_mprice1.setForeground(new java.awt.Color(153, 153, 153));
        label_mprice1.setText("Quantity");
        order_bg.add(label_mprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        label_mprice2.setBackground(new java.awt.Color(51, 51, 51));
        label_mprice2.setForeground(new java.awt.Color(153, 153, 153));
        label_mprice2.setText("Current Order");
        order_bg.add(label_mprice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        size_label.setBackground(new java.awt.Color(51, 51, 51));
        size_label.setForeground(new java.awt.Color(153, 153, 153));
        size_label.setText("Size");
        order_bg.add(size_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        table_scrollpane2.setBackground(new java.awt.Color(255, 255, 255));
        table_scrollpane2.setBorder(null);
        table_scrollpane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_scrollpane2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        order_table_pname.setAutoCreateRowSorter(true);
        order_table_pname.setBackground(new java.awt.Color(255, 255, 255));
        order_table_pname.setForeground(new java.awt.Color(51, 51, 51));
        order_table_pname.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        order_table_pname.setFocusable(false);
        order_table_pname.setName(""); // NOI18N
        order_table_pname.setRowHeight(30);
        order_table_pname.getTableHeader().setReorderingAllowed(false);
        table_scrollpane2.setViewportView(order_table_pname);
        table.setRowHeight(table.getRowHeight()+20);

        order_bg.add(table_scrollpane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 360, 190));

        category_txt.setBackground(new java.awt.Color(51, 51, 51));
        category_txt.setForeground(new java.awt.Color(153, 153, 153));
        category_txt.setText("Category");
        order_bg.add(category_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        time_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        time_label.setForeground(new java.awt.Color(51, 51, 51));
        time_label.setText("Time:");
        order_bg.add(time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 60, 30));

        actual_time_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        actual_time_label.setForeground(new java.awt.Color(51, 51, 51));
        order_bg.add(actual_time_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 140, 30));

        receipt_area.setBackground(new java.awt.Color(255, 255, 255));
        receipt_area.setColumns(20);
        receipt_area.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        receipt_area.setRows(5);
        receipt_area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        receipt_area.setFocusable(false);
        jScrollPane1.setViewportView(receipt_area);

        order_bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 290, 400));
        order_bg.add(cash_txtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 90, 40));

        total_text.setForeground(new java.awt.Color(153, 153, 153));
        total_text.setText("Total: ");
        order_bg.add(total_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 40, 40));

        cash_text.setForeground(new java.awt.Color(153, 153, 153));
        cash_text.setText("Cash:");
        order_bg.add(cash_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 40, 40));

        total_label.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        total_label.setForeground(new java.awt.Color(51, 51, 51));
        order_bg.add(total_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 60, 40));

        change_label.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        change_label.setForeground(new java.awt.Color(51, 51, 51));
        change_label.setVisible(false);
        order_bg.add(change_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 60, 40));

        orderAdd_button.setBackground(new java.awt.Color(187, 111, 26));
        orderAdd_button.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        orderAdd_button.setForeground(new java.awt.Color(240, 240, 240));
        orderAdd_button.setText("Add");
        orderAdd_button.setAlignmentY(0.0F);
        orderAdd_button.setBorder(null);
        orderAdd_button.setBorderPainted(false);
        orderAdd_button.setContentAreaFilled(false);
        orderAdd_button.setFocusPainted(false);
        orderAdd_button.setFocusable(false);
        orderAdd_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderAdd_button.setIconTextGap(0);
        orderAdd_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        orderAdd_button.setOpaque(true);
        orderAdd_button.setPreferredSize(new java.awt.Dimension(180, 40));
        orderAdd_button.setRequestFocusEnabled(false);
        orderAdd_button.setRolloverEnabled(false);
        orderAdd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderAdd_buttonActionPerformed(evt);
            }
        });
        order_bg.add(orderAdd_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 80, 40));
        ButtonMouseListener add_listener = new ButtonMouseListener(orderAdd_button);
        orderAdd_button.addMouseListener(add_listener);

        orderReset_button.setBackground(new java.awt.Color(187, 111, 26));
        orderReset_button.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        orderReset_button.setForeground(new java.awt.Color(240, 240, 240));
        orderReset_button.setText("Reset");
        orderReset_button.setAlignmentY(0.0F);
        orderReset_button.setBorder(null);
        orderReset_button.setBorderPainted(false);
        orderReset_button.setContentAreaFilled(false);
        orderReset_button.setFocusPainted(false);
        orderReset_button.setFocusable(false);
        orderReset_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderReset_button.setIconTextGap(0);
        orderReset_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        orderReset_button.setOpaque(true);
        orderReset_button.setPreferredSize(new java.awt.Dimension(180, 40));
        orderReset_button.setRequestFocusEnabled(false);
        orderReset_button.setRolloverEnabled(false);
        orderReset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderReset_buttonActionPerformed(evt);
            }
        });
        order_bg.add(orderReset_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 100, 40));
        ButtonMouseListener reset_listener = new ButtonMouseListener(orderReset_button);
        orderReset_button.addMouseListener(reset_listener);

        orderRemove_button.setBackground(new java.awt.Color(187, 111, 26));
        orderRemove_button.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        orderRemove_button.setForeground(new java.awt.Color(240, 240, 240));
        orderRemove_button.setText("Remove");
        orderRemove_button.setAlignmentY(0.0F);
        orderRemove_button.setBorder(null);
        orderRemove_button.setBorderPainted(false);
        orderRemove_button.setContentAreaFilled(false);
        orderRemove_button.setFocusPainted(false);
        orderRemove_button.setFocusable(false);
        orderRemove_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderRemove_button.setIconTextGap(0);
        orderRemove_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        orderRemove_button.setOpaque(true);
        orderRemove_button.setPreferredSize(new java.awt.Dimension(180, 40));
        orderRemove_button.setRequestFocusEnabled(false);
        orderRemove_button.setRolloverEnabled(false);
        orderRemove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderRemove_buttonActionPerformed(evt);
            }
        });
        order_bg.add(orderRemove_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 100, 40));
        ButtonMouseListener remove_listener = new ButtonMouseListener(orderRemove_button);
        orderRemove_button.addMouseListener(remove_listener);

        receipt_button.setBackground(new java.awt.Color(187, 111, 26));
        receipt_button.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        receipt_button.setForeground(new java.awt.Color(240, 240, 240));
        receipt_button.setText("Print Receipt");
        receipt_button.setAlignmentY(0.0F);
        receipt_button.setBorder(null);
        receipt_button.setBorderPainted(false);
        receipt_button.setContentAreaFilled(false);
        receipt_button.setFocusPainted(false);
        receipt_button.setFocusable(false);
        receipt_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        receipt_button.setIconTextGap(0);
        receipt_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        receipt_button.setOpaque(true);
        receipt_button.setPreferredSize(new java.awt.Dimension(180, 40));
        receipt_button.setRequestFocusEnabled(false);
        receipt_button.setRolloverEnabled(false);
        receipt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receipt_buttonActionPerformed(evt);
            }
        });
        order_bg.add(receipt_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 100, 40));
        ButtonMouseListener receipt_listener = new ButtonMouseListener(receipt_button);
        receipt_button.addMouseListener(receipt_listener);

        orderClear_button.setBackground(new java.awt.Color(187, 111, 26));
        orderClear_button.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        orderClear_button.setForeground(new java.awt.Color(240, 240, 240));
        orderClear_button.setText("Clear");
        orderClear_button.setAlignmentY(0.0F);
        orderClear_button.setBorder(null);
        orderClear_button.setBorderPainted(false);
        orderClear_button.setContentAreaFilled(false);
        orderClear_button.setFocusPainted(false);
        orderClear_button.setFocusable(false);
        orderClear_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        orderClear_button.setIconTextGap(0);
        orderClear_button.setMargin(new java.awt.Insets(2, 10, 3, 14));
        orderClear_button.setOpaque(true);
        orderClear_button.setPreferredSize(new java.awt.Dimension(180, 40));
        orderClear_button.setRequestFocusEnabled(false);
        orderClear_button.setRolloverEnabled(false);
        orderClear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderClear_buttonActionPerformed(evt);
            }
        });
        order_bg.add(orderClear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 80, 40));
        ButtonMouseListener clear_listener = new ButtonMouseListener(orderClear_button);
        orderClear_button.addMouseListener(clear_listener);

        order_panel.add(order_bg, java.awt.BorderLayout.CENTER);

        main_panel.add(order_panel, "order_card");

        menu_panel.setBackground(new java.awt.Color(240, 240, 240));
        menu_panel.setLayout(new java.awt.BorderLayout());

        menu_title.setBackground(new java.awt.Color(187, 111, 26));
        menu_title.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        menu_title.setForeground(new java.awt.Color(255, 255, 255));
        menu_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_title.setText("MENU");
        menu_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu_title.setOpaque(true);
        menu_title.setPreferredSize(new java.awt.Dimension(0, 60));
        menu_panel.add(menu_title, java.awt.BorderLayout.PAGE_START);

        mcontent_panel.setBackground(new java.awt.Color(255, 255, 255));
        mcontent_panel.setForeground(new java.awt.Color(255, 255, 255));
        mcontent_panel.setFocusable(false);
        mcontent_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        category_combobox.setBackground(new java.awt.Color(255, 255, 255));
        category_combobox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        category_combobox.setForeground(new java.awt.Color(51, 51, 51));
        category_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milk Tea", "Iced Coffee", "Fruit Tea", "Hot Brew", "Praf", "Add-Ons" }));
        category_combobox.setFocusable(false);
        category_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_comboboxActionPerformed(evt);
            }
        });
        mcontent_panel.add(category_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 220, 40));

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigBrew/icons/add.png"))); // NOI18N
        add_button.setText("Add");
        add_button.setFocusable(false);
        add_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add_button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add_button.setIconTextGap(10);
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        mcontent_panel.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, 40));

        edit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigBrew/icons/edit.png"))); // NOI18N
        edit_button.setText("Edit");
        edit_button.setFocusable(false);
        edit_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        edit_button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        edit_button.setIconTextGap(8);
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });
        mcontent_panel.add(edit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, 40));

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bigBrew/icons/delete.png"))); // NOI18N
        delete_button.setText("Delete");
        delete_button.setFocusable(false);
        delete_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        delete_button.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });
        mcontent_panel.add(delete_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, 40));

        table_scrollpane.setBackground(new java.awt.Color(255, 255, 255));
        table_scrollpane.setBorder(null);
        table_scrollpane.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table_scrollpane.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        table.setAutoCreateRowSorter(true);
        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setForeground(new java.awt.Color(51, 51, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Medio Price", "Grande Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setName(""); // NOI18N
        table.setRowHeight(15);
        table.getTableHeader().setReorderingAllowed(false);
        table_scrollpane.setViewportView(table);
        table.setRowHeight(table.getRowHeight()+20);

        mcontent_panel.add(table_scrollpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 730, 250));

        menu_panel.add(mcontent_panel, java.awt.BorderLayout.CENTER);

        modification_panel.setBackground(new java.awt.Color(187, 111, 26));
        modification_panel.setPreferredSize(new java.awt.Dimension(0, 260));
        modification_panel.setLayout(new java.awt.CardLayout());

        empty_panel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout empty_panelLayout = new javax.swing.GroupLayout(empty_panel);
        empty_panel.setLayout(empty_panelLayout);
        empty_panelLayout.setHorizontalGroup(
            empty_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        empty_panelLayout.setVerticalGroup(
            empty_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        modification_panel.add(empty_panel, "empty_card");

        add_panel.setBackground(new java.awt.Color(255, 255, 255));

        bg_panel.setBackground(new java.awt.Color(255, 255, 255));
        bg_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        bg_panel.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 21, -1, 31));

        add_text.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        add_text.setForeground(new java.awt.Color(30, 30, 30));
        add_text.setText("Add New Item");
        bg_panel.add(add_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, 179, -1));

        add_cbb.setBackground(new java.awt.Color(255, 255, 255));
        add_cbb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        add_cbb.setForeground(new java.awt.Color(51, 51, 51));
        add_cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milk Tea", "Iced Coffee", "Fruit Tea", "Hot Brew", "Praf", "Add-Ons" }));
        add_cbb.setFocusable(false);
        add_cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cbbActionPerformed(evt);
            }
        });
        bg_panel.add(add_cbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 38, 220, 40));

        tf_bgpanel.setBackground(new java.awt.Color(255, 255, 255));
        tf_bgpanel.setOpaque(false);
        tf_bgpanel.setLayout(new java.awt.CardLayout());

        add_tf1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        add_tf2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        add_tf3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout three_tfLayout = new javax.swing.GroupLayout(three_tf);
        three_tf.setLayout(three_tfLayout);
        three_tfLayout.setHorizontalGroup(
            three_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, three_tfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(add_tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        three_tfLayout.setVerticalGroup(
            three_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, three_tfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(three_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(three_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(add_tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        tf_bgpanel.add(three_tf, "card3");

        javax.swing.GroupLayout two_tfLayout = new javax.swing.GroupLayout(two_tf);
        two_tf.setLayout(two_tfLayout);
        two_tfLayout.setHorizontalGroup(
            two_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, two_tfLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(add_tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(add_tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        two_tfLayout.setVerticalGroup(
            two_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(two_tfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(two_tfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tf_bgpanel.add(two_tf, "card2");

        bg_panel.add(tf_bgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 117, 594, 52));

        label_name.setBackground(new java.awt.Color(51, 51, 51));
        label_name.setForeground(new java.awt.Color(153, 153, 153));
        label_name.setText("Product Name");
        bg_panel.add(label_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        label_mprice.setBackground(new java.awt.Color(51, 51, 51));
        label_mprice.setForeground(new java.awt.Color(153, 153, 153));
        label_mprice.setText("Medio Price");
        bg_panel.add(label_mprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        label_gprice.setBackground(new java.awt.Color(51, 51, 51));
        label_gprice.setForeground(new java.awt.Color(153, 153, 153));
        label_gprice.setText("Grande Price");
        bg_panel.add(label_gprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        label_category.setBackground(new java.awt.Color(51, 51, 51));
        label_category.setForeground(new java.awt.Color(153, 153, 153));
        label_category.setText("Category");
        bg_panel.add(label_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        label_name1.setBackground(new java.awt.Color(51, 51, 51));
        label_name1.setForeground(new java.awt.Color(153, 153, 153));
        label_name1.setText("Product Name");
        bg_panel.add(label_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        label_price.setBackground(new java.awt.Color(51, 51, 51));
        label_price.setForeground(new java.awt.Color(153, 153, 153));
        label_price.setText("Price");
        bg_panel.add(label_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        javax.swing.GroupLayout add_panelLayout = new javax.swing.GroupLayout(add_panel);
        add_panel.setLayout(add_panelLayout);
        add_panelLayout.setHorizontalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_panelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(bg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        add_panelLayout.setVerticalGroup(
            add_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_panelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(bg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        add_panel.setVisible(false);

        modification_panel.add(add_panel, "add_card");

        edit_panel.setBackground(new java.awt.Color(255, 255, 255));

        bg_panel1.setBackground(new java.awt.Color(255, 255, 255));
        bg_panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });
        bg_panel1.add(update_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 21, -1, 31));

        update_txt.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        update_txt.setForeground(new java.awt.Color(30, 30, 30));
        update_txt.setText("Update Item");
        bg_panel1.add(update_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, -1, -1));

        update_cbb.setBackground(new java.awt.Color(255, 255, 255));
        update_cbb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        update_cbb.setForeground(new java.awt.Color(51, 51, 51));
        update_cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milk Tea", "Iced Coffee", "Fruit Tea", "Hot Brew", "Praf", "Add-Ons" }));
        update_cbb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        update_cbb.setFocusable(false);
        update_cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_cbbActionPerformed(evt);
            }
        });
        bg_panel1.add(update_cbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 38, 220, 40));

        item_cbb.setBackground(new java.awt.Color(255, 255, 255));
        item_cbb.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        item_cbb.setForeground(new java.awt.Color(50, 50, 50));
        DatabaseHandler.editComboBox(update_cbb,item_cbb);
        item_cbb.setFocusable(false);
        bg_panel1.add(item_cbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 38, 220, 40));

        tf_bgpanel1.setBackground(new java.awt.Color(255, 204, 204));
        tf_bgpanel1.setLayout(new java.awt.CardLayout());

        edit_tf1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        edit_tf2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout two_tf1Layout = new javax.swing.GroupLayout(two_tf1);
        two_tf1.setLayout(two_tf1Layout);
        two_tf1Layout.setHorizontalGroup(
            two_tf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(two_tf1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(edit_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(edit_tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        two_tf1Layout.setVerticalGroup(
            two_tf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(two_tf1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(two_tf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tf_bgpanel1.add(two_tf1, "card3");

        javax.swing.GroupLayout one_tf1Layout = new javax.swing.GroupLayout(one_tf1);
        one_tf1.setLayout(one_tf1Layout);
        one_tf1Layout.setHorizontalGroup(
            one_tf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(one_tf1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(edit_tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        one_tf1Layout.setVerticalGroup(
            one_tf1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(one_tf1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(edit_tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tf_bgpanel1.add(one_tf1, "card2");

        bg_panel1.add(tf_bgpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 420, 50));

        label_newGprice.setBackground(new java.awt.Color(51, 51, 51));
        label_newGprice.setForeground(new java.awt.Color(153, 153, 153));
        label_newGprice.setText("New Grande Price");
        bg_panel1.add(label_newGprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        label_name2.setBackground(new java.awt.Color(51, 51, 51));
        label_name2.setForeground(new java.awt.Color(153, 153, 153));
        label_name2.setText("Product Name");
        bg_panel1.add(label_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        label_category1.setBackground(new java.awt.Color(51, 51, 51));
        label_category1.setForeground(new java.awt.Color(153, 153, 153));
        label_category1.setText("Category");
        bg_panel1.add(label_category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        label_newPrice.setBackground(new java.awt.Color(51, 51, 51));
        label_newPrice.setForeground(new java.awt.Color(153, 153, 153));
        label_newPrice.setText("New Price");
        bg_panel1.add(label_newPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        label_newMprice.setBackground(new java.awt.Color(51, 51, 51));
        label_newMprice.setForeground(new java.awt.Color(153, 153, 153));
        label_newMprice.setText("New Medio Price");
        bg_panel1.add(label_newMprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        javax.swing.GroupLayout edit_panelLayout = new javax.swing.GroupLayout(edit_panel);
        edit_panel.setLayout(edit_panelLayout);
        edit_panelLayout.setHorizontalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(bg_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        edit_panelLayout.setVerticalGroup(
            edit_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_panelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(bg_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        modification_panel.add(edit_panel, "edit_card");

        menu_panel.add(modification_panel, java.awt.BorderLayout.PAGE_END);
        menu_panel.add(modification_panel, java.awt.BorderLayout.SOUTH);

        main_panel.add(menu_panel, "menu_card");

        history_panel.setBackground(new java.awt.Color(240, 240, 240));
        history_panel.setLayout(new java.awt.BorderLayout());

        history_title.setBackground(new java.awt.Color(187, 111, 26));
        history_title.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 30)); // NOI18N
        history_title.setForeground(new java.awt.Color(255, 255, 255));
        history_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        history_title.setText("ORDER HISTORY");
        history_title.setOpaque(true);
        history_title.setPreferredSize(new java.awt.Dimension(0, 60));
        history_panel.add(history_title, java.awt.BorderLayout.PAGE_START);

        history_bgPanel.setBackground(new java.awt.Color(255, 255, 255));
        history_bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        history_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Product Name", "Size", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(history_table);
        DatabaseHandler.orderHistory(history_table);

        history_bgPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 680, 520));

        history_panel.add(history_bgPanel, java.awt.BorderLayout.CENTER);

        main_panel.add(history_panel, "history_card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(side_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    ///////////// METHODS //////////////////
    
    private void order_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_buttonActionPerformed
        card.show (main_panel, "order_card");
        DatabaseHandler.orderUpdateProductName(order_category_cbb, order_table_pname);
    }//GEN-LAST:event_order_buttonActionPerformed

    private void menu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buttonActionPerformed
        card.show (main_panel, "menu_card");
        DatabaseHandler.updateTableData(category_combobox, table);
    }//GEN-LAST:event_menu_buttonActionPerformed

    private void history_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history_buttonActionPerformed
        card.show (main_panel, "history_card");
    }//GEN-LAST:event_history_buttonActionPerformed

    private void orderAdd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderAdd_buttonActionPerformed
        DatabaseHandler.addOrder(order_category_cbb,order_size_cbb, order_table_pname, currentOrder_table, qty_spinner,  currentDate);
        DatabaseHandler.calculateTotal(currentOrder_table,total_label);
        
    }//GEN-LAST:event_orderAdd_buttonActionPerformed

    private void category_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_comboboxActionPerformed
        DatabaseHandler.updateTableData(category_combobox, table);
    }//GEN-LAST:event_category_comboboxActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        menu.show (modification_panel, "add_card");
        label_name1.setVisible(false);
        label_price.setVisible(false);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
       
        DatabaseHandler.deleteItem (table, category_combobox);
        DatabaseHandler.updateTableData(category_combobox, table);
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void add_cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cbbActionPerformed
       
        String selectedValue = add_cbb.getSelectedItem().toString();
        
        if (selectedValue.equals("Hot Brew") || selectedValue.equals("Add-Ons")){
            add_fields.show (tf_bgpanel, "card2");
            
            label_name.setVisible(false);
            label_mprice.setVisible(false);
            label_gprice.setVisible(false);
            label_name1.setVisible(true);
            label_price.setVisible(true);
        } else {
            add_fields.show (tf_bgpanel, "card3");
            
            label_name.setVisible(true);
            label_mprice.setVisible(true);
            label_gprice.setVisible(true);
            label_name1.setVisible(false);
            label_price.setVisible(false);
            
        }
    }//GEN-LAST:event_add_cbbActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
       
        DatabaseHandler.addItem(add_cbb, add_tf1, add_tf4, add_tf2, add_tf3, add_tf5);
        DatabaseHandler.updateTableData(category_combobox, table);
       
    }//GEN-LAST:event_save_btnActionPerformed

    private void update_cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_cbbActionPerformed
        String selectedValue = update_cbb.getSelectedItem().toString();
        if (selectedValue.equals("Hot Brew") || selectedValue.equals("Add-Ons")){
            edit_fields.show (tf_bgpanel1, "card2");
        
            label_newMprice.setVisible(false);
            label_newGprice.setVisible(false);
            label_newPrice.setVisible(true);
        }else {
            edit_fields.show (tf_bgpanel1, "card3");
            
            label_newMprice.setVisible(true);
            label_newGprice.setVisible(true);
            label_newPrice.setVisible(false);
        }
        DatabaseHandler.editComboBox(update_cbb,item_cbb);
        
    }//GEN-LAST:event_update_cbbActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
           
           DatabaseHandler.editItem(update_cbb, item_cbb, edit_tf1, edit_tf2, edit_tf3);
           DatabaseHandler.updateTableData(category_combobox, table);
    }//GEN-LAST:event_update_buttonActionPerformed

    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        menu.show (modification_panel, "edit_card");
        
        label_newPrice.setVisible(false);
    }//GEN-LAST:event_edit_buttonActionPerformed

    private void order_category_cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_category_cbbActionPerformed
        DatabaseHandler.orderUpdateProductName(order_category_cbb, order_table_pname);
        DatabaseHandler.orderUpdateSize(order_category_cbb, order_size_cbb);
        
    }//GEN-LAST:event_order_category_cbbActionPerformed

    private void logOut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOut_buttonActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure to log out?", "Log Out", JOptionPane.YES_NO_OPTION); // yes == 0
            
            if (option == 0){ //yes
                dispose();
                LogIn_Page logInPage = new LogIn_Page();
                logInPage.setVisible(true);
            }
            
    }//GEN-LAST:event_logOut_buttonActionPerformed

    private void orderReset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderReset_buttonActionPerformed
        receipt_area.setText(" ");
        cash_txtField.setText("");
        total_label.setText("");
        change_label.setText("");
        currentOrder_table.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Product Name", "Size", "Quantity", "Price"
        }
    ));
    }//GEN-LAST:event_orderReset_buttonActionPerformed

    private void orderRemove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderRemove_buttonActionPerformed
        DatabaseHandler.deleteCurrentOrder (currentOrder_table, total_label);
    }//GEN-LAST:event_orderRemove_buttonActionPerformed

    private void receipt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receipt_buttonActionPerformed
        if (currentOrder_table.getRowCount() == 0)
           JOptionPane.showMessageDialog(null, "Add items to order.", "Error", JOptionPane.ERROR_MESSAGE);
       else if (cash_txtField.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Please input cash value.", "Error", JOptionPane.ERROR_MESSAGE);
       else if (Double.parseDouble(total_label.getText()) > Double.parseDouble(cash_txtField.getText()))         // Display an error message if the total is higher than the cash
                        JOptionPane.showMessageDialog(null, "Insufficient cash value.", "Error", JOptionPane.ERROR_MESSAGE);    
       else
        {
            DatabaseHandler.calculateChange(cash_txtField, total_label, change_label);
            receipt();
            DatabaseHandler.saveOrder(currentOrder_table, currentDate, cash_txtField);
            currentOrder_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Size", "Quantity", "Price"
                }
            ));
            cash_txtField.setText("");
            total_label.setText("");
            change_label.setText("");
            
            DatabaseHandler.orderHistory(history_table);
        }// TODO add your handling code here:
    }//GEN-LAST:event_receipt_buttonActionPerformed

    private void orderClear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderClear_buttonActionPerformed
        receipt_area.setText(" ");// TODO add your handling code here:
    }//GEN-LAST:event_orderClear_buttonActionPerformed

    
    
    
    // Shows the date and time in the order card
    public  void setDateTime(){
        new Thread(new Runnable(){
            @Override
            public void run(){
                while(true){
                    try{
                        Thread.sleep(1000);
                    
                }   catch (InterruptedException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                        currentDate = LocalDate.now();
                        LocalTime currentTime = LocalTime.now();

                        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("h:mm:ss a");
                        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("EEEE, MM-dd-yyyy");

                        String formattedTime = currentTime.format(timeFormatter);
                        String formattedDate = currentDate.format(dateFormatter);

                        actual_time_label.setText(formattedTime);
                        actual_date_label.setText(formattedDate);
                    }
            }
        }).start();   
    }
    
    // Prints the receipt: Formatting the texts
    public void receipt(){
        
        String cash = cash_txtField.getText();
        String total = total_label.getText();
        String change = change_label.getText();
        
        
            String receipt_text = " \t               Big Brew  \n"
                            + " \t  Malolos, Bulacan, Philippines \n"
                            + "\t     Bulacan State University \n\n"
                            + "  Date:   " + actual_date_label.getText() + "   "
                            + "  Time:   " + actual_time_label.getText() + "\n"
                            + " ===========================================\n"
                            + "   Order Format: Product Name - Size - Qty. - Price \n" 
                            + " ===========================================\n";
                            
            DefaultTableModel modeltable = (DefaultTableModel) currentOrder_table.getModel();
            // Iterate through the rows to accumulate information
            for (int i = 0; i < currentOrder_table.getRowCount(); i++) {
                String name = modeltable.getValueAt(i, 0).toString();
                String size = modeltable.getValueAt(i, 1).toString();
                int quantity = (int) modeltable.getValueAt(i, 2);
                String stringValue = (String) modeltable.getValueAt(i, 3);
                double price = Double.parseDouble(stringValue);

                // Accumulate the information
                receipt_text += "-  " + name + "  -  " + size + "  -  " + quantity + "  -  " + price + "\n";
            }
            // Set the text after the loop

            String receipt_text1 = "\n\n\n ===========================================\n"
                         + "   CASH: \t" + cash + "\n"
                         + "   TOTAL: \t" + total + "\n"
                         + "   CHANGE:   " + change + "\n"
                         + " ===========================================\n"
                         + "          THANK YOU FOR YOUR PURCHACE!";

            receipt_area.setText(receipt_text + receipt_text1);
        
    }
    
    
    
    
    ////////////////////////////////// MAIN //////////////////////////////////////
    
    public static void main(String args[]) {
        // Enables the Nimbus Look and Feel
      try {
        for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {    
    } // end of nimbus   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LogIn_Page().setVisible(true);
                //new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actual_date_label;
    private javax.swing.JLabel actual_time_label;
    private javax.swing.JButton add_button;
    private javax.swing.JComboBox<String> add_cbb;
    private javax.swing.JPanel add_panel;
    private javax.swing.JLabel add_text;
    private javax.swing.JTextField add_tf1;
    private javax.swing.JTextField add_tf2;
    private javax.swing.JTextField add_tf3;
    private javax.swing.JTextField add_tf4;
    private javax.swing.JTextField add_tf5;
    private javax.swing.JPanel bg_panel;
    private javax.swing.JPanel bg_panel1;
    private javax.swing.JLabel brand_logo;
    private javax.swing.JLabel brand_name;
    private javax.swing.JLabel cash_text;
    private javax.swing.JTextField cash_txtField;
    private javax.swing.JComboBox<String> category_combobox;
    private javax.swing.JLabel category_txt;
    private javax.swing.JLabel change_label;
    private javax.swing.JTable currentOrder_table;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton edit_button;
    private javax.swing.JPanel edit_panel;
    private javax.swing.JTextField edit_tf1;
    private javax.swing.JTextField edit_tf2;
    private javax.swing.JTextField edit_tf3;
    private javax.swing.JPanel empty_panel;
    private javax.swing.JPanel history_bgPanel;
    private javax.swing.JButton history_button;
    private javax.swing.JPanel history_panel;
    private javax.swing.JTable history_table;
    private javax.swing.JLabel history_title;
    private javax.swing.JComboBox<String> item_cbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_category;
    private javax.swing.JLabel label_category1;
    private javax.swing.JLabel label_gprice;
    private javax.swing.JLabel label_mprice;
    private javax.swing.JLabel label_mprice1;
    private javax.swing.JLabel label_mprice2;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_name1;
    private javax.swing.JLabel label_name2;
    private javax.swing.JLabel label_newGprice;
    private javax.swing.JLabel label_newMprice;
    private javax.swing.JLabel label_newPrice;
    private javax.swing.JLabel label_price;
    private javax.swing.JLabel line;
    private javax.swing.JButton logOut_button;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel mcontent_panel;
    private javax.swing.JButton menu_button;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JLabel menu_title;
    private javax.swing.JPanel modification_panel;
    private javax.swing.JPanel one_tf1;
    private javax.swing.JButton orderAdd_button;
    private javax.swing.JButton orderClear_button;
    private javax.swing.JButton orderRemove_button;
    private javax.swing.JButton orderReset_button;
    private javax.swing.JPanel order_bg;
    private javax.swing.JButton order_button;
    private javax.swing.JComboBox<String> order_category_cbb;
    private javax.swing.JPanel order_panel;
    private javax.swing.JComboBox<String> order_size_cbb;
    private javax.swing.JTable order_table_pname;
    private javax.swing.JScrollPane order_table_scrollpane;
    private javax.swing.JLabel order_title;
    private javax.swing.JSpinner qty_spinner;
    private javax.swing.JTextArea receipt_area;
    private javax.swing.JButton receipt_button;
    private javax.swing.JButton save_btn;
    private javax.swing.JPanel side_panel;
    private javax.swing.JLabel size_label;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane table_scrollpane;
    private javax.swing.JScrollPane table_scrollpane2;
    private javax.swing.JPanel tf_bgpanel;
    private javax.swing.JPanel tf_bgpanel1;
    private javax.swing.JPanel three_tf;
    private javax.swing.JLabel time_label;
    private javax.swing.JLabel total_label;
    private javax.swing.JLabel total_text;
    private javax.swing.JPanel two_tf;
    private javax.swing.JPanel two_tf1;
    private javax.swing.JButton update_button;
    private javax.swing.JComboBox<String> update_cbb;
    private javax.swing.JLabel update_txt;
    // End of variables declaration//GEN-END:variables

}